name: Generate GitHub Activity Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/github-activity.yml'

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create dist directory
        run: mkdir -p dist

      - name: Generate GitHub Activity Streak
        uses: muhammad-fiaz/github-readme-streak-stats@v1.0.1
        with:
          USERNAME: PERIYASAMY-N
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          THEME: tokyonight
          HIDE_BORDER: true
          OUTPUT_PATH: dist/github-activity.svg

      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
